from collections.abc import Callable
from typing import TypeVar

from openai import AsyncOpenAI, OpenAIError
from pydantic import BaseModel

from app.core.config import settings

SchemaT = TypeVar("SchemaT", bound=BaseModel)


class LLMServiceError(RuntimeError):
    """Base error for structured LLM generation failures."""


class MissingAPIKeyError(LLMServiceError):
    pass


class LLMResponseError(LLMServiceError):
    pass


MockResponseFactory = Callable[[type[SchemaT]], SchemaT]


class LLMService:
    def __init__(
        self,
        *,
        api_key: str | None = None,
        model: str | None = None,
        mock_response_factory: MockResponseFactory | None = None,
    ) -> None:
        self.api_key = api_key if api_key is not None else settings.openai_api_key
        self.model = model or settings.openai_model
        self.mock_response_factory = mock_response_factory

    async def generate_structured(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
        response_model: type[SchemaT],
    ) -> SchemaT:
        if self.mock_response_factory is not None:
            return self.mock_response_factory(response_model)

        if not self.api_key:
            raise MissingAPIKeyError(
                "OPENAI_API_KEY is not configured. Add it to backend/.env "
                "before calling an LLM parsing endpoint."
            )

        client = AsyncOpenAI(
            api_key=self.api_key,
            timeout=15,
            max_retries=1,
        )
        try:
            completion = await client.beta.chat.completions.parse(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                response_format=response_model,
                temperature=0,
            )
        except OpenAIError as exc:
            raise LLMServiceError(
                "Structured data could not be generated by the LLM provider."
            ) from exc
        finally:
            await client.close()

        if not completion.choices:
            raise LLMResponseError("The LLM returned no structured output.")
        message = completion.choices[0].message
        if message.refusal:
            raise LLMResponseError(f"The LLM refused the request: {message.refusal}")
        if message.parsed is None:
            raise LLMResponseError(
                "The LLM returned no schema-valid structured output."
            )
        return message.parsed
